SET(FBX_FOUND FALSE)
SET(FBX_INCLUDE_DIR "NOTFOUND")
SET(FBX_LIBRARIES "NOTFOUND")

IF( WIN32 )
	FIND_PATH(FBX_SDK_DIR include/fbxsdk.h PATHS
		"[HKEY_LOCAL_MACHINE\\SOFTWARE\\Autodesk FBX SDK 2011.3.1;Install_Dir]"
		"[HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\Autodesk FBX SDK 2011.3.1;Install_Dir]")

	IF(FBX_SDK_DIR)
		SET(FBX_FOUND TRUE)	
		IF( MSVC80 )
			FIND_LIBRARY(FBX_LIBRARY fbxsdk_20113_1.lib PATHS "${FBX_SDK_DIR}\\lib\\vs2005")
			FIND_LIBRARY(FBX_DEBUG_LIBRARY fbxsdk_20113_1d.lib PATHS "${FBX_SDK_DIR}\\lib\\vs2005")
			SET(FBX_LIBRARY_DIR "${FBX_SDK_DIR}\\lib\\vs2005")
		ENDIF( MSVC80 )	
	
		IF( MSVC90 )
			FIND_LIBRARY(FBX_LIBRARY fbxsdk_20113_1.lib PATHS "${FBX_SDK_DIR}\\lib\\vs2008")
			FIND_LIBRARY(FBX_DEBUG_LIBRARY fbxsdk_20113_1d.lib PATHS "${FBX_SDK_DIR}\\lib\\vs2008")
			SET(FBX_LIBRARY_DIR "${FBX_SDK_DIR}\\lib\\vs2008")
		ENDIF( MSVC90 )	
	
		IF( MSVC10 )
			FIND_LIBRARY(FBX_LIBRARY fbxsdk_20113_1.lib PATHS "${FBX_SDK_DIR}\\lib\\vs2010")
			FIND_LIBRARY(FBX_DEBUG_LIBRARY fbxsdk_20113_1d.lib PATHS "${FBX_SDK_DIR}\\lib\\vs2010")
			SET(FBX_LIBRARY_DIR "${FBX_SDK_DIR}\\lib\\vs2010")
		ENDIF( MSVC10 )
	
		SET(FBX_LIBRARIES ${FBX_LIBRARY} ${FBX_DEBUG_LIBRARY})
		SET(FBX_INCLUDE_DIR "${FBX_SDK_DIR}\\include")
	ENDIF( FBX_SDK_DIR )
	
ENDIF( WIN32 )

IF(FBX_FOUND)
    MESSAGE(STATUS "Found Autodesk FBX SDK")
ELSE(FBX_FOUND)
    MESSAGE(FATAL_ERROR "Could NOT find Autodesk FBX SDK. Please make sure the FBX SDK 2011.3.1 or higher is installed.")
ENDIF(FBX_FOUND)