SET(DOXYGEN_FOUND FALSE)
SET(DOXYGEN_EXECUTABLE "NOTFOUND")

IF( WIN32 )
	FIND_PROGRAM(DOXYGEN_EXECUTABLE NAMES doxygen PATHS
		"[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\doxygen_is1;Inno Setup: App Path]\\bin"
		"[HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\doxygen_is1;Inno Setup: App Path]\\bin")
	IF( DOXYGEN_EXECUTABLE )
		SET(DOXYGEN_FOUND TRUE)
	ENDIF( DOXYGEN_EXECUTABLE )
ENDIF( WIN32 )

IF(DOXYGEN_FOUND)
    MESSAGE(STATUS "Found Doxygen")
ELSE(DOXYGEN_FOUND)
    MESSAGE(FATAL_ERROR "Could NOT find Doxygen.")
ENDIF(DOXYGEN_FOUND)