SET(FBX_FOUND FALSE)
SET(FBX_INCLUDE_DIR "NOTFOUND")
SET(FBX_LIBRARIES "NOTFOUND")

IF( WIN32 )
	FIND_PATH(FBX_SDK_DIR include/fbxsdk.h PATHS
		"[HKEY_LOCAL_MACHINE\\SOFTWARE\\Autodesk FBX SDK 2012.1;Install_Dir]"
		"[HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\Autodesk FBX SDK 2012.1;Install_Dir]")

	IF(FBX_SDK_DIR)
		SET(FBX_FOUND TRUE)	
		IF( MSVC10 )
			FIND_LIBRARY(FBX_LIBRARY fbxsdk-2012.1-md.lib PATHS "${FBX_SDK_DIR}\\lib\\vs2010\\x86")
			FIND_LIBRARY(FBX_DEBUG_LIBRARY fbxsdk-2012.1-mdd.lib PATHS "${FBX_SDK_DIR}\\lib\\vs2010\\x86")
			SET(FBX_LIBRARY_DIR "${FBX_SDK_DIR}\\lib\\vs2010\\x86")
		ENDIF( MSVC10 )
	
		SET(FBX_LIBRARIES ${FBX_LIBRARY} ${FBX_DEBUG_LIBRARY})
		SET(FBX_INCLUDE_DIR "${FBX_SDK_DIR}\\include")
	ENDIF( FBX_SDK_DIR )
	
ENDIF( WIN32 )

IF(FBX_FOUND)
    MESSAGE(STATUS "Found Autodesk FBX SDK")
ELSE(FBX_FOUND)
    MESSAGE(FATAL_ERROR "Could NOT find Autodesk FBX SDK. Please make sure the FBX SDK 2012.1 or higher is installed.")
ENDIF(FBX_FOUND)