SET(FREEIMAGE_FOUND FALSE)
SET(FREEIMAGE_INCLUDE_DIR "NOTFOUND")
SET(FREEIMAGE_LIBRARIES "NOTFOUND")

IF( WIN32 )
	FIND_PATH(FREEIMAGE_SDK_DIR Dist\\FreeImage.dll PATHS
	"$ENV{PROGRAMFILES}\\FreeImage"
	"$ENV{PROGRAMW6432}\\FreeImage"
	)
	
	IF(FREEIMAGE_SDK_DIR)
		SET(FREEIMAGE_FOUND TRUE)
		SET(FREEIMAGE_INCLUDE_DIR "${FREEIMAGE_SDK_DIR}\\dist")
		SET(FREEIMAGE_LIBRARY_DIR "${FREEIMAGE_SDK_DIR}\\dist")
		FIND_LIBRARY(FREEIMAGE_LIBRARY NAMES FreeImage.lib PATHS "${FREEIMAGE_SDK_DIR}\\dist")
		
	ELSE(FREEIMAGE_SDK_DIR)
		SET(FREEIMAGE_FOUND FALSE)
	ENDIF(FREEIMAGE_SDK_DIR)	

ENDIF( WIN32 )

IF(FREEIMAGE_FOUND)
    MESSAGE(STATUS "Found FreeImage")
ELSE(FREEIMAGE_FOUND)
    MESSAGE(FATAL_ERROR "Could NOT find FreeImage.")
ENDIF(FREEIMAGE_FOUND)