SET(BULLET_FOUND FALSE)
SET(BULLET_INCLUDE_DIR "NOTFOUND")
SET(BULLET_LIBRARIES "NOTFOUND")

IF(WIN32)

FIND_PATH(BULLET_SDK_DIR lib\\Release\\BulletDynamics.lib PATHS
"$ENV{PROGRAMFILES}\\BULLET_PHYSICS"
"$ENV{PROGRAMW6432}\\BULLET_PHYSICS"
)

IF(BULLET_SDK_DIR)
    SET(BULLET_FOUND TRUE)
	SET(BULLET_LIBRARY_DIR "${BULLET_SDK_DIR}\\lib")
    SET(BULLET_INCLUDE_DIR "${BULLET_SDK_DIR}\\include\\bullet")
	FIND_LIBRARY(BULLET_LIBRARY BulletDynamics.lib PATHS "${BULLET_LIBRARY_DIR}\\Release")
	FIND_LIBRARY(BULLET_DEBUG_LIBRARY BulletDynamics.lib PATHS "${BULLET_LIBRARY_DIR}\\Debug")
    SET(BULLET_LIBRARIES ${BULLET_LIBRARY})
ELSE(BULLET_SDK_DIR)
    SET(BULLET_FOUND FALSE)
ENDIF(BULLET_SDK_DIR)

ENDIF(WIN32)

IF(BULLET_FOUND)
    MESSAGE(STATUS "Found Bullet")
ELSE(BULLET_FOUND)
    MESSAGE(FATAL_ERROR "Could NOT find Bullet.")
ENDIF(BULLET_FOUND)